@startuml

object "<u>php_demo1:Folder</u>" as php_demo1 {
    name = "php_demo1"
}
object "<u>sourceFiles:Folder</u>" as sourceFiles {
    name = "Source Files"
}
object "<u>includePath:Folder</u>" as includePath {
    name = "Include Path"
}
object "<u>remoteFiles:Folder</u>" as remoteFiles {
    name = "Remote Files"
}
object "<u>phalcon:Folder</u>" as phalcon {
    name = ".phalcon"
}
object "<u>cache:Folder</u>" as cache {
    name = "cache"
}
object "<u>public:Folder</u>" as public {
    name = "public"
}
object "<u>htaccess:File</u>" as htaccess {
    name = ".htaccess"
}
object "<u>htrouter:File</u>" as htrouter {
    name = ".htrouter.php"
}
object "<u>index:File</u>" as index{
    name = "index.html"
}

php_demo1 *-- sourceFiles
php_demo1 *-- includePath
php_demo1 *-- remoteFiles

sourceFiles *-- phalcon
sourceFiles *-- cache
sourceFiles *-- public

public *-- htaccess
public *-- htrouter
public *-- index

@enduml
